// Pure functions: WizardState -> TOML string. Mirrors the formatting
// style of pitboss_cli::manifest::init_template (Simple/Full templates)
// so the wizard's output looks like something an engineer would have
// hand-written.
//
// Sections are emitted in canonical order: [run] -> [defaults] ->
// ([lead] | [[task]]). No empty sections. No sub-sections beyond what
// the wizard collects (advanced sections live in the editor).

import type { WizardState } from './state';

export function composeToml(state: WizardState): string {
  const sections: string[] = [];

  sections.push(header(state));
  sections.push(runSection(state));
  sections.push(defaultsSection(state));
  if (state.mode === 'flat') {
    for (const t of state.tasks) {
      sections.push(taskSection(t));
    }
  } else {
    sections.push(leadSection(state));
  }

  return sections.join('\n') + '\n';
}

function header(state: WizardState): string {
  return [
    `# Pitboss manifest — generated by the console wizard.`,
    `# Run "pitboss validate <this-file>" to verify, then dispatch from`,
    `# the editor. Every available field is documented in`,
    `# docs/manifest-reference.toml.`,
    `# Filename: ${state.filename}.toml`
  ].join('\n');
}

function runSection(state: WizardState): string {
  const lines: string[] = ['[run]'];
  lines.push(`name             = ${tomlString(state.run_name)}`);
  lines.push(`worktree_cleanup = "on_success"`);
  return lines.join('\n');
}

function defaultsSection(state: WizardState): string {
  const lines: string[] = ['[defaults]'];
  lines.push(`model        = ${tomlString(state.model)}`);
  lines.push(`effort       = ${tomlString(state.effort)}`);
  lines.push(`tools        = ${tomlStringArray(state.tools)}`);
  lines.push(`use_worktree = ${state.use_worktree}`);
  if (state.timeout_secs !== null && state.timeout_secs > 0) {
    lines.push(`timeout_secs = ${state.timeout_secs}`);
  }
  return lines.join('\n');
}

function taskSection(t: { id: string; directory: string; prompt: string }): string {
  const lines: string[] = ['[[task]]'];
  lines.push(`id        = ${tomlString(t.id)}`);
  lines.push(`directory = ${tomlString(t.directory)}`);
  lines.push(`prompt    = ${tomlMultiline(t.prompt)}`);
  return lines.join('\n');
}

function leadSection(state: WizardState): string {
  const l = state.lead;
  const lines: string[] = ['[lead]'];
  lines.push(`id        = ${tomlString(l.id)}`);
  lines.push(`directory = ${tomlString(l.directory)}`);
  lines.push(`prompt    = ${tomlMultiline(l.prompt)}`);
  lines.push('');
  lines.push('# Lead-level caps (required when the lead spawns workers).');
  lines.push(`max_workers       = ${l.max_workers}`);
  lines.push(`budget_usd        = ${l.budget_usd.toFixed(2)}`);
  lines.push(`lead_timeout_secs = ${l.lead_timeout_secs}`);
  return lines.join('\n');
}

// ---- TOML primitive emitters --------------------------------------------

/**
 * Emit a TOML basic string. Escapes `"`, `\`, and newlines so the
 * round-trip through the validator is lossless. Single-line only —
 * call `tomlMultiline` for prompts.
 */
function tomlString(s: string): string {
  const escaped = s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
  return `"${escaped}"`;
}

function tomlStringArray(items: string[]): string {
  if (items.length === 0) return '[]';
  return `[${items.map(tomlString).join(', ')}]`;
}

/**
 * Emit a TOML multi-line basic string (`"""..."""`). If the prompt
 * fits on one line and contains no double-quotes, fall back to the
 * single-line form for cleaner output.
 */
function tomlMultiline(s: string): string {
  if (!s.includes('\n') && !s.includes('"')) {
    return tomlString(s);
  }
  // Inside a """...""" block, only `\` and `"""` need escaping.
  // The leading newline after the opening fence is stripped by TOML
  // parsers, so include it deliberately for readability.
  const escaped = s.replace(/\\/g, '\\\\').replace(/"""/g, '\\"\\"\\"');
  return `"""\n${escaped}\n"""`;
}
